"""initial schema

Revision ID: 7bde613df1cf
Revises: 
Create Date: 2026-09-04 17:19:04.478822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bde613df1cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('hub_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installs_hub_id'), 'installs', ['hub_id'], unique=True)
    op.create_table('associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('from_object_type', sa.String(), nullable=False),
    sa.Column('from_hubspot_id', sa.String(), nullable=False),
    sa.Column('to_object_type', sa.String(), nullable=False),
    sa.Column('to_hubspot_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['installs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('hubspot_object_id', sa.String(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('hs_created_at', sa.DateTime(), nullable=True),
    sa.Column('hs_updated_at', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['installs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('install_id', 'hubspot_object_id')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_table('contacts',
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('lifecyclestage', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('hubspot_object_id', sa.String(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('hs_created_at', sa.DateTime(), nullable=True),
    sa.Column('hs_updated_at', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['installs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('install_id', 'hubspot_object_id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_table('deals',
    sa.Column('dealname', sa.String(), nullable=True),
    sa.Column('dealstage', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('pipeline', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('hubspot_object_id', sa.String(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('hs_created_at', sa.DateTime(), nullable=True),
    sa.Column('hs_updated_at', sa.DateTime(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['installs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('install_id', 'hubspot_object_id')
    )
    op.create_index(op.f('ix_deals_dealstage'), 'deals', ['dealstage'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('install_id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_upserted', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['install_id'], ['installs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('install_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('subscription_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_error', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['installs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_events')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_deals_dealstage'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('associations')
    op.drop_index(op.f('ix_installs_hub_id'), table_name='installs')
    op.drop_table('installs')
    # ### end Alembic commands ###
