"""add object_type to webhook_events

Revision ID: 9caea1554d23
Revises: 7bde613df1cf
Create Date: 2026-09-05 14:08:57.291379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9caea1554d23'
down_revision: Union[str, Sequence[str], None] = '7bde613df1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('object_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_events', 'object_type')
    # ### end Alembic commands ###
